### ISSUE TITLE
Unable to find V2

### ISSUE THREAD

**Issue by tim-xergy** [sergotail/laravel-pint-action#3]
```
[Pint](https://github.com/Xergy-Group/proteus-api/actions/runs/12066672659/job/33648023633#step:1:36)
Unable to resolve action `sergotail/laravel-pint-action@v2`, unable to find version `v2`
```

```yml
  Pint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39

      - name: Run Laravel Pint
        uses: sergotail/laravel-pint-action@v2
        with:
          onlyFiles: ${{ steps.changed-files.outputs.all_changed_files }}
          testMode: true
          verboseMode: true
          configPath: ./pint.json
          preset: laravel
          onlyDirty: false
          annotate: true
          pintVersion: 1.8.0
          annotateVersion: 1.8.5
          useComposer: true
   ```
